# Generated by Django 4.1 on 2022-10-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=16)),
                ('descripcion', models.TextField(max_length=32)),
                ('precio', models.IntegerField()),
                ('imagen', models.TextField(max_length=128)),
            ],
        ),
    ]
